module.exports = {
	'likes': '{ likes, number } me gusta',
	'logout': 'Salir',
	'english': 'Inglés',
	'spanish': 'Español',
	'signup.subheading': 'Regístrate para ver fotos de tus amigos estudiando en Platzi',
	'signup.facebook': 'Iniciar sesión con Facebook',
	'signup.text': 'Iniciar sesión',
	'email': 'Correo Electrónico',
	'username': 'Nombre de Usuario',
	'fullname': 'Nombre Completo',
	'password': 'Contraseña',
	'signup.call-to-action': 'Regístrate',
	'signup.have-account': '¿Tienes una cuenta?',
	'signin': 'Entrar',
	'signin.already-have-account': '¿No tienes una cuenta?',
	'language': ' Idioma',
	'upload-picture': 'Subir foto',
	'upload': 'Subir'
}